#!/bin/bash

iconsAc=( "" "" "" "" "" )
iconsM=''
iconsDc=( "" "" "" "" "" "" "" "" "" "" )
iconsLayout=''
iconsWifi=''
iconsVpn=' vpn'

WIFI(){
wifi=$(nmcli d wifi | grep "^\*" | grep -v "\*.*SSID" | awk '{ print $8 }')
}

MEMORY(){
MEM=$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')
}

BATTERY(){
BAT_STATE=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/state/{print $2}')
BAT_PERC=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage/{print $2}' | tr -d %)

# Charging icons
if [ $BAT_STATE = 'charging' ]; then
    i=$((BAT_PERC/20))
    BAT_ICON=${iconsAc[$i]}
# Fully charged icon
elif [ $BAT_STATE = 'fully-charged' ]; then
    BAT_ICON=''
# Discharging icons
else
    # For 100% battery
    if [ $BAT_PERC -eq 100 ]; then
    BAT_ICON=${iconsDc[9]}
# For below 100% battery
else
    i=$((BAT_PERC/10))
    BAT_ICON=${iconsDc[$i]}
    fi
fi
}

LAYOUT(){
layout=$(setxkbmap -query | grep layout | rev | cut -c1-2 | rev)
}

VPNSTATUS(){
vpnstatus=$(vpnstatus | grep "\DNS" | cut -c 5-)

if [[ $vpnstatus = 'OK' ]]; then
    vpn=$iconsVpn
else
    vpn=""
fi
sleep 10
}

i3status | (read line; echo "$line"; read line ; echo "$line" ; read line ; echo "$line" ; while true
do
  read line

# Wifi
WIFI
# Memory
MEMORY
# Battery
BATTERY
# Layout
LAYOUT
# Vpn status
VPNSTATUS

echo -e ",[\
  {\"full_text\":\"${iconsLayout} $layout\" },\
  {\"full_text\":\"${BAT_ICON} $BAT_PERC%\" },\
  {\"full_text\":\"${iconsM} ${MEM}\" },\
  {\"full_text\":\"${iconsWifi} ${wifi}\" },\
  {\"full_text\":\"$vpn\" },\
    ${line#,\[}"

done)

exit 0
