#!/bin/sh
PN=~/documents/notes/
touch $PN/readme.md
echo "# NotesMenu" > $PN/readme.md
TR="kitty sh -c"
ED="nano -cix"

QT=$(ls $PN | wc -l)
setxkbmap -layout us,ru
CHOISE=$(find $PN*.md -maxdepth 0 -type f | awk -F '/' '{print $NF;}' | dmenu -fn 'Iosevka Medium-10' -nf '#888888' -nb '#222222' -sb '#5195E3' -sf '#FFFFFF' -i -p "$QT notes " -f) || exit 1
if [[ "$CHOISE" != *.md ]]; then
    CHOISE="$CHOISE.md"
fi
CHOISE="$ED '$PN$CHOISE'"
$TR "$CHOISE"
