#!/bin/zsh
general {
        colors = true
        interval = 5
        output_format = i3bar
}

order += "wireless _first_"
order += "disk /home/"
order += "tztime local"

wireless _first_ {
        format_up = "%quality"
        format_down = ""
}

disk "/home/" {
        format = " %free"
}

battery all {
        format = "%status %percentage"
        format_down = "No battery"
        status_chr = "⚡"
        status_bat = " $BAT_ICON"
        status_unk = "?"
        status_full = ""
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 10
}

tztime local {
        format = " %d.%m  %H:%M "
}

volume master {
    format = " %volume"
    format_muted = "婢 "
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}
