#!/bin/zsh
# Logo key. Use Mod1 for Alt.
   set $mod Mod4
# Home row direction keys, like vim
   set $left h
   set $down j
   set $up k
   set $right l
# Use Mouse+$mod to drag floating windows to their wanted position
   floating_modifier $mod
# Your preferred terminal emulator
   set $term terminator -T Terminal
# Dmenu
   set $menu --no-startup-id dmenu_run -fn 'Iosevka Medium-10'
# App
   set $screenshot scrot $HOME/screenshots/`date +%Y-%m-%d_%H:%M:%S`.png
   set $screenshotu scrot -u $HOME/screenshots/`date +%Y-%m-%d_%H:%M:%S`.png
   set $buffer xclip -o | sed -n 1p | xargs
# Font
   font pango:Iosevka Medium 9
# Wallpaper
   set $wallpaper /home/mat/documents/wallpapers/arch-lamp.png
   exec_always feh --bg-scale $wallpaper
# Key bindings
# Basics:

    # start a terminal
    bindsym $mod+Return exec $term

    # kill focused window
#    bindsym $mod+q kill
    bindcode $mod+24 kill

    # start your launcher
    bindsym $mod+d exec $menu
    bindsym $mod+Shift+d exec --no-startup-id dmenu_extended_run

    # reload the configuration file
    bindsym $mod+Shift+c reload

#
# Gaps
   for_window [class="^.*"] border pixel 2

   gaps outer 2
   gaps inner 4
#
# Moving around:
    # Move your focus around
    bindsym $mod+$left focus left
    bindsym $mod+$down focus down
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right
    # or use $mod+[up|down|left|right]
    bindsym $mod+Left focus left
    bindsym $mod+Down focus down
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right
    # _move_ the focused window with the same, but add Shift
    bindsym $mod+Shift+$left move left
    bindsym $mod+Shift+$down move down
    bindsym $mod+Shift+$up move up
    bindsym $mod+Shift+$right move right
    # ditto, with arrow keys
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right
#
# Workspaces:
    set $ws1 "1:work  "
    set $ws2 "2:browser  "
    set $ws3 "3:mind  "
    set $ws4 "4:music  "
    set $ws5 5
    set $ws6 6
    set $ws7 7
    set $ws8 "8:remote linux  "
    set $ws9 "9:remote windows  "

    # switch to workspace
    bindsym $mod+1 workspace $ws1
    bindsym $mod+2 workspace $ws2
    bindsym $mod+3 workspace $ws3
    bindsym $mod+4 workspace $ws4
    bindsym $mod+5 workspace $ws5
    bindsym $mod+6 workspace $ws6
    bindsym $mod+7 workspace $ws7
    bindsym $mod+8 workspace $ws8
    bindsym $mod+9 workspace $ws9
    # move focused container to workspace
    bindsym $mod+Shift+1 move container to workspace $ws1
    bindsym $mod+Shift+2 move container to workspace $ws2
    bindsym $mod+Shift+3 move container to workspace $ws3
    bindsym $mod+Shift+4 move container to workspace $ws4
    bindsym $mod+Shift+5 move container to workspace $ws5
    bindsym $mod+Shift+6 move container to workspace $ws6
    bindsym $mod+Shift+7 move container to workspace $ws7
    bindsym $mod+Shift+8 move container to workspace $ws8
    bindsym $mod+Shift+9 move container to workspace $ws9
    # Note: workspaces can have any name you want, not just numbers.
    # We just use 1-10 as the default.

    # Switch the current container between different layout styles
    bindsym $mod+s layout stacking
    bindsym $mod+w layout tabbed
    bindsym $mod+e layout toggle split

    # Make the current focus fullscreen
    bindsym $mod+f fullscreen

    # Toggle the current focus between tiling and floating mode
    bindsym $mod+Shift+space floating toggle

    # Swap focus between the tiling area and the floating area
    bindsym $mod+space focus mode_toggle

    # move focus to the parent container
    bindsym $mod+a focus parent
#
# Scratchpad:
    # You can send windows there and get them back later.
    # Move the currently focused window to the scratchpad
    bindsym $mod+Shift+minus move scratchpad
    # Show the next scratchpad window or hide the focused scratchpad window.
    # If there are multiple scratchpad windows, this command cycles through them.
    bindsym $mod+minus scratchpad show
#
# Resizing containers:
bindsym $mod+r mode "resize"

mode "resize" {
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    # ditto, with arrow keys
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    # return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

# Audio volume
   bindsym XF86AudioRaiseVolume exec --no-startup-id amixer -c 0 -q set Master 2dB+ unmute
   bindsym XF86AudioLowerVolume exec --no-startup-id amixer -c 0 -q set Master 2db- unmute
   bindsym XF86AudioMute exec --no-startup-id amixer -q set Master toggle
# Keyboard layout
   bindsym Caps_Lock exec ~/.config/i3status/scripts/keyboard_layout.sh cycle us ru
#
# Status Bar:
bar {
    position top
    status_command i3status | ~/.config/i3status/scripts/keyboard_layout.sh i3status
    tray_output none
colors {
    separator #5294e2
    background #222222
    statusline #5294e2
    focused_workspace #5294e2 #5294e2 #ffffff
    active_workspace #5294e2 #5294e2 #ffffff
    inactive_workspace #333333 #333333 #888888
    urgent_workspace #5294e2 #5294e2 #ffffff
       }
}
# My binds
# App
    bindsym $mod+b exec firefox
    bindsym Print exec $screenshot
    bindsym $mod+Print exec $screenshotu
    bindsym $mod+y exec $buffer mpv
    bindsym $mod+Shift+y exec $buffer youtube-dl
# Start windows
#
    for_window [class="firefox"] move to workspace $ws2
    for_window [class="Simplenote"] move to workspace $ws3
    for_window [class="Spotify"] move to workspace $ws4
    for_window [class="Telegram"] move to workspace $ws4
    for_window [class="Telegram"] resize set 350px
    for_window [class="Remmina"] move to workspace $ws9

# Screen changer
#
set $changescreen screen: [1]laptop [2]monitor [3]laptop+monitor [4]2monitors
bindsym $mod+p mode "$changescreen"
mode "$changescreen" {
    bindsym 1 exec xrandr --output eDP1 --mode 1366x768 --output HDMI1 --off & feh --bg-scale $wallpaper
    bindsym 2 exec xrandr --output eDP1 --off --output HDMI1 --mode 1920x1080 & feh --bg-scale $wallpaper
    bindsym 3 exec xrandr --output eDP1 --mode 1366x768 --output HDMI1 --mode 1920x1080 --right-of eDP1 & feh --bg-scale $wallpaper
    bindsym 4 exec xrandr --output HDMI1 --mode 1920x1080 --output DP1 --mode 1920x1080 --right-of HDMI1 & feh --bg-scale $wallpaper

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
# Power off
#
set $poweroff screen: [1]poweroff [2]reboot [3]lock
   bindsym $mod+Escape mode "$poweroff"

mode "$poweroff" {
   bindsym 1 exec systemctl poweroff
   bindsym 2 exec systemctl reboot
   bindsym 3 exec i3lock -i $wallpaper 

   bindsym Escape mode "default"
   bindsym Return mode "default"
}
